### ISSUE TITLE
Add simple install instructions

### ISSUE THREAD

**Issue by AbdealiJK** [saurfang/spark-sas7bdat#13]
It would be worthwhile to also mention a few steps for pyspark as I want to use it with pyspark, and can't seem to be able to get it running. Read https://github.com/databricks/spark-csv/issues/59#issuecomment-99291210 for various suggestions, of which some are applicable here too

Also, it would be good to provide a method which does not use maven with `--packages` as some people have proxies which does not allow maven. Hence, a small section on which jar files to download and how to configure pyspark/spark-shell to use these jars would be very helpful !

**Comment by chappers** [comment]
I think this should actually work out of the box with a fat jar that you create using `sbt assembly`; you should be able to add this via `--jars spark-sas7bdat-assembly-XXX.jar`

This is off the spark 2.0 update I made, but it should work for 1.6 as well. 

See screenshot below:

![image](https://cloud.githubusercontent.com/assets/2498638/20458898/6106467e-af05-11e6-9d64-7b13976c739b.png)

Code:

Run `pyspark` with `jars`:

```
bin\pyspark --jars spark-sas7bdat-assembly-1.1.4_2.0.0.jar
```

Within interactive session:

```
df = sqlContext.read.format("com.github.saurfang.sas.spark").load("iris.sas7bdat")
df.printSchema()
```
