### ISSUE TITLE
Issues with Spark-sas7bdat

### ISSUE THREAD

**Issue by cyberyu** [saurfang/spark-sas7bdat#14]
Please check these issues I found in my work, thanks!

https://eilianyu.wordpress.com/2016/10/27/be-aware-of-hidden-data-errors-using-spark-sas7bdat-pacakge-to-ingest-sas-datasets-to-spark/

**Comment by saurfang** [comment]
Thanks for investigating. These likely can be fixed by upgrading parso #10. However I don't have the bandwidth to do it myself. Contribution is welcomed.

**Comment by saurfang** [comment]
I believe
