### ISSUE TITLE
Parso Library upgraded : Please merge pull request

### ISSUE THREAD

**Issue by alvinhenrick** [saurfang/spark-sas7bdat#20]
Hi , My friend Huaxin sent you the pull request  https://github.com/saurfang/spark-sas7bdat/pulls . 
He has updated the Parso library . Would you please consider merging it and pushing to the repository.

Appreciate your help.

Thanks!
Alvin.

**Comment by saurfang** [comment]
Sorry for the delay. I have responded with some comments. Feel free to join discussion at the PR instead of opening new issue.
