### ISSUE TITLE
Not able to read all records from SAS dataset.

### ISSUE THREAD

**Issue by NeerajBhadani** [saurfang/spark-sas7bdat#22]
Hi Team,
   I am trying to use this package and able to read the sas data into spark as DataFrame. However, not able to read entire sas data into dataframe. when I using version (1.1.5-s_2.11), I am not able to read the last 3 rows from the sas dfataset. PFB few scenarios

1. sas dataset has 100 records, df.show(97) works fine. However, df.show(98) hangs.
2. sas dataset has 50 records, df.show(47) works fine. However, df.show(48) hangs.
3. sas dataset has 19 records, df.show(16) works fine. However, df.show(17) hangs.

similaryly, for package : 1.1.5-s_2.11, last 2 records are creating an issue.
1. sas dataset has 100 records, df.show(98) works fine. However, df.show(99) hangs.
2. sas dataset has 50 records, df.show(48) works fine. However, df.show(49) hangs.
3. sas dataset has 19 records, df.show(17) works fine. However, df.show(18) hangs.

Could you please help here to resolve this issue.

Looking forward to hear from team.

Regards,
Neeraj

**Comment by NabilKem** [comment]
I have the same issue, Dataframe.show(Nbr record - 3) works fine, but not Dataframe.show(Nbr record - 1)

Any idea why is that!?
Regards

**Comment by saurfang** [comment]
Please give the new version a try as we believe this might have been fixed.
