### ISSUE TITLE
SasFileParser: Failed to read page from file

### ISSUE THREAD

**Issue by jt999** [saurfang/spark-sas7bdat#24]
Hi

I have uploaded a sas7bdat file into hdfs, and am trying to use the sas7bdat library to read this file into a spark dataframe (using pyspark)

Code is quite straight forward:

![image](https://user-images.githubusercontent.com/18142822/28620547-b148cb40-720d-11e7-8b3b-468862819eb9.png)

ps....I can confirm that the file exists:

![image](https://user-images.githubusercontent.com/18142822/28620580-d7f4b54c-720d-11e7-8c95-84a34d9306d5.png)

**Comment by saurfang** [comment]
Please give the new version a try as we believe this might have been fixed.
