### ISSUE TITLE
Issue regarding reading of sas7bdat file and then converting it into csv file.

### ISSUE THREAD

**Issue by tilwani** [saurfang/spark-sas7bdat#25]
I am attempting to convert a .sas7bdat file into .csv using pyspark. I intended to use the spark-sas7bdat for creating a spark dataframe from the sas7bdat file and then using the package spark-csv to write and save it as a csv file. 
When i use the command: 
[_df = sqlContext.read.format("com.github.saurfang.sas.spark").load("filename.sas7bdat")_] ..no error is thrown and the command runs very quickly, but after that when i try to run df.count() method on it, it throws a big error in a lot of lines, something like SasFileParser error, and also when i try to save it as a csv file using the command: [_df.write.csv('filename.csv')_] or the command [_df.write.format('com.databricks.spark.csv').save('mycsv.csv')_], the task does not completes and is stuck without giving any output or any error. The process gets stuck for hours even for very small files like 30MB. I intend to use it for larger files but first tried to test it for small files. The image shows the resources issue which i overcame using larger nodes. But even then it stucks. Can someone please tell what can be the possible reason and the solution for this.
![capture](https://user-images.githubusercontent.com/14253521/31187506-c928c2aa-a94f-11e7-91c6-fd4f05bb7c20.PNG)

**Comment by saurfang** [comment]
Please give the new version a try as we believe this might have been fixed.
