### ISSUE TITLE
Willing to migrate license to Apache 2.0?

### ISSUE THREAD

**Issue by Tagar** [saurfang/spark-sas7bdat#27]
https://github.com/epam/parso/issues/19

The upstream Parso library is migrating to Apache license. 
Can the same be done with saurfang/spark-sas7bdat? 
Not sure if Apache and GPL licenses are compatible.
Another benefit, is that with Apache license saurfang/spark-sas7bdat could potentially be included into core Apache Spark.

**Comment by saurfang** [comment]
Yes I prefer(ed) Apache 2.0 and had to license under GPL originally because they were incompatible.

**Comment by Tagar** [comment]
Cool - thank you.

**Comment by printsev** [comment]
parso 2.0.8 was released with new ALv2 license

**Comment by saurfang** [comment]
@Tagar happy new year! Any news on release of your PR?

**Comment by saurfang** [comment]
Done
