### ISSUE TITLE
Implicit import not working in spark 1.4.0

### ISSUE THREAD

**Issue by revolucion09** [saurfang/spark-sas7bdat#3]
I can't get to work:
val df = sqlContext.read.format("com.github.saurfang.sas.spark").load("cars.sas7bdat")

Getting:
java.lang.RuntimeException: Failed to load class for data source: com.github.saurfang.sas.spark

Working fine if importing in the explicit way:
import com.github.saurfang.sas.spark._
and using sasFile()

Other modules such as spark-csv are working fine with the load.format() method, to ensure it is not a local issue.

**Comment by saurfang** [comment]
Ah. It turns out I never implemented that part. Sorry I guess you will have to use the `sasFile` for now. If you want to use native SQL query you can register the dataframe as a table in Scala. I might be able to find some time this weekend for this.

**Comment by saifellafi** [comment]
Thank you, looking forward to it!
ps: (Same user reporter)

**Comment by saurfang** [comment]
Should worked now. I have released the changes in version 1.1.3. Can you please try and let me know if it works for you?

**Comment by saifellafi** [comment]
Thank you, will let you know as soon as I try it back.
