### ISSUE TITLE
Cannot read file from Azure Blob Path

### ISSUE THREAD

**Issue by angel-hernandez91** [saurfang/spark-sas7bdat#49]
I attempted to read a SAS dataset from an Azure Blob path, but I am getting the following error:

`shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container <my-container> in account <my-account>.blob.core.windows.net not found, and we can&apos;t create it using anoynomous credentials, and no credentials found for them in the configuration.`

I have configured my credentials using:
`spark.conf.set(
  "fs.azure.account.key.{}.blob.core.windows.net".format(account_name),
  account_key
)`

And I can correctly `ls` the path I'm trying to read from using `dbutils.fs.ls`. So it seems as though the error is with the package.

Package: 2.1.0-s_2.11
Platform: Databricks
Spark Version: Latest stable (Scala 2.11)
Python Version: 3.5

**Comment by thesuperzapper** [comment]
If you put another file type (e.g. parquet) in the same blob store, are you able to read it with that config set?

**Comment by angel-hernandez91** [comment]
> If you put another file type (e.g. parquet) in the same blob store, are you able to read it with that config set?

Yes I am. So it turns out the credentials needed to be set differently for the SAS reader since it's using the Spark Context as opposed to the Spark Session variable.

I was able to set the credentials using: `sc._jsc.hadoopConfiguration().set("fs.azure.account.key.{}.blob.core.windows.net".format(account_name), account_key)`

I imagine the same would work from an S3 path. 

So I guess this can be marked as resolved. It would be great to add this tidbit of information regarding the credentials to the README docs.

**Comment by Antalares** [comment]
Hi,

I'm facing the same issue.
The command "sc._jsc.hadoopConfiguration().set("fs.azure.account.key.{}.blob.core.windows.net".format(account_name), account_key)" can resolve this issue but this implies storing credential on cluster and not only for spark session.

There is a workaround byusing following command ?
spark.conf.set( "fs.azure.account.key.{}.blob.core.windows.net".format(account_name), account_key )

Thank you
