### ISSUE TITLE
Not all records from SAS file being loaded into DataFrame

### ISSUE THREAD

**Issue by westonsankey** [saurfang/spark-sas7bdat#52]
I'm running into an issue where the DataFrame is missing a small percentage (0.05%) of records when using the library to load from a SAS file. I ran a test just using the Parso library, and it was able to read all of the records. Additionally, I tried using the sas7bdat Python library and that was able to read all of the data as well.

**Comment by thesuperzapper** [comment]
Can you provide a sas file (without sensitive data) which has this issue?

If possible, also provide a CSV version so we can see which rows get dropped .

**Comment by westonsankey** [comment]
Unfortunately I can't provide the SAS file, as it contains sensitive information. Was hoping that you have possibly heard of this issue and could point me in the right direction.

I tried setting the `minSplitSize` so that it forces a single partition, but that resulted in the same incorrect number of records.

**Comment by westonsankey** [comment]
I did some additional troubleshooting and this appears to be a Parso issue.

**Comment by thesuperzapper** [comment]
@westonsankey even though you can't provide that specific file, can you create a new file which also has that issue, and then submit it on the parso issue tracker?

**Comment by marchub** [comment]
I have a similar issue in that we read a large SAS file with 2.1.0 and it works  but misses a few rows. It appears that the rows we miss at the ones that were appended or modified later manually via the SAS UI by users. Is this an issue with Parso missing these modified/appended rows? Or is this related to spark-sas7bdat?

@westonsankey did you find the source of your issue? It might be related. Thanks.

**Comment by thesuperzapper** [comment]
@marchub can you raise an new GitHub Issue, with an example file displaying the behaviour you reported?

Preferably, could you also upload a CSV version of file, so we can see what it should contain?
