### ISSUE TITLE
spark-sas7bdat wins WiseWithData ELEVATE Award

### ISSUE THREAD

**Issue by ianjghent** [saurfang/spark-sas7bdat#60]
Please excuse the use of an issue for this. Forest @saurfang, you have been awarded the [WiseWithData ELEVATE OSS Maintainer of the Year award](https://www.wisewithdata.com/2020/09/elevate-humanitarian-oss-award-winners/). We've reached out via LinkedIn, but we haven't got a response and we can't find an email. Please email me at ian.ghent@wisewithdata.com to claim your award.

**Comment by saurfang** [comment]
Thanks for reaching ou. I'm flattered and will get in touch offline :)
