### ISSUE TITLE
undoumented changes in NEWS.md

### ISSUE THREAD

**Issue by thesuperzapper** [saurfang/spark-sas7bdat#61]
I believe that we might have forgot to include the gzip feature found in PR #50 to the 3.0.0 release NEWS.md

**Comment by thesuperzapper** [comment]
@saurfang

**Comment by thesuperzapper** [comment]
Also, we might want to consider updating the README.md requirements and compatibility matrix to state we no longer support Spark versions before `2.4.X`.

As you can see we are now doing travis matrix with `2.4.6` (which only guarantees support for Spark `2.4.X`)

**Comment by saurfang** [comment]
Good catch! Done 🙏
