### ISSUE TITLE
Parso error

### ISSUE THREAD

**Issue by harrysouthworth** [saurfang/spark-sas7bdat#7]
Hello. I just stumbled on this repo.

In case you don't know, there are cases where Parso silently does the wrong thing:
https://github.com/BioStatMatt/sas7bdat.parso/issues/5

No news since July on when it's getting fixed.

Harry

**Comment by saurfang** [comment]
Thanks for the info! If you can point me to any of the fixes that should be applied on the parso side, I'm glad to incorporate them into my fork. I had to fork the **SasFileParser** class already due to various issues around S3, stackoverflow exceptions and etc.

**Comment by harrysouthworth** [comment]
There haven't been any fixes. The guy from the company who created parso
said it would be fixed in a month or two, but that was in July. I checked
their website a couple of weeks ago, but the version of parso hasn't
changed for a couple of years.

He does give a clue about what the problem is in his posts in
sas7bdat.parso: "the number is bigger than Long.MAX_VALUE". I tried to
build parso myself, but it failed and I'm not a Java guy, so I gave up
quickly.

I've been trying this last few days to overcome the problem with quoted
newstrings in the CSV, and other issues around quotes appearing in text
fields. You can find my efforts in unsas on the sqlite branch (
https://github.com/harrysouthworth/unsas/tree/sqlite), but it's incomplete
and I'm not a Java programmer, so it's messy, slow and can no doubt be
improved in a hundred ways (not least by putting a decent CSV parser in
there).

If a fix for the Long.MAX_VALUE thing shows up, I'll let you know.

Harry

**Comment by saurfang** [comment]
#10 will hopefully solve this.
