### ISSUE TITLE
Using spark-sas7bdat with Spark-1.5.0 yields java.lang.ClassCastException

### ISSUE THREAD

**Issue by akellers** [saurfang/spark-sas7bdat#8]
I can create a dataframe from a SAS file suing spark-shell with your package using `val df = sqlContext.sasFile("data/sample3.sas7bdat")`. It returns a `org.apache.spark.sql.DataFrame = [String: string, Integer: double, Float: double]`.

But calling `df.count` yields in an exception: `java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.GenericMutableRow cannot be cast to org.apache.spark.sql.Row`.

Any ideas what's going wrong here?

**Comment by saurfang** [comment]
Thanks for reporting. Should be fixed. Let me know if you still have any issues.

**Comment by akellers** [comment]
Work's fine! Thanks.
